/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsIndexRouteImport } from './routes/documents/index'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents/$documentId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ClientsClientIdEngagementsRouteImport } from './routes/clients/$clientId/engagements'
import { Route as ClientsClientIdDocumentsRouteImport } from './routes/clients/$clientId/documents'
import { Route as ClientsClientIdEngagementsEngagementIdRouteImport } from './routes/clients/$clientId/engagements/$engagementId'
import { Route as AdminUsersUserIdAssignmentsRouteImport } from './routes/admin/users/$userId/assignments'
import { Route as ClientsClientIdEngagementsEngagementIdDocumentsIndexRouteImport } from './routes/clients/$clientId/engagements/$engagementId/documents/index'
import { Route as ClientsClientIdEngagementsEngagementIdDocumentsNewRouteImport } from './routes/clients/$clientId/engagements/$engagementId/documents/new'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdEngagementsRoute =
  ClientsClientIdEngagementsRouteImport.update({
    id: '/$clientId/engagements',
    path: '/$clientId/engagements',
    getParentRoute: () => ClientsRoute,
  } as any)
const ClientsClientIdDocumentsRoute =
  ClientsClientIdDocumentsRouteImport.update({
    id: '/$clientId/documents',
    path: '/$clientId/documents',
    getParentRoute: () => ClientsRoute,
  } as any)
const ClientsClientIdEngagementsEngagementIdRoute =
  ClientsClientIdEngagementsEngagementIdRouteImport.update({
    id: '/$engagementId',
    path: '/$engagementId',
    getParentRoute: () => ClientsClientIdEngagementsRoute,
  } as any)
const AdminUsersUserIdAssignmentsRoute =
  AdminUsersUserIdAssignmentsRouteImport.update({
    id: '/$userId/assignments',
    path: '/$userId/assignments',
    getParentRoute: () => AdminUsersRoute,
  } as any)
const ClientsClientIdEngagementsEngagementIdDocumentsIndexRoute =
  ClientsClientIdEngagementsEngagementIdDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => ClientsClientIdEngagementsEngagementIdRoute,
  } as any)
const ClientsClientIdEngagementsEngagementIdDocumentsNewRoute =
  ClientsClientIdEngagementsEngagementIdDocumentsNewRouteImport.update({
    id: '/documents/new',
    path: '/documents/new',
    getParentRoute: () => ClientsClientIdEngagementsEngagementIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/clients': typeof ClientsRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/documents/': typeof DocumentsIndexRoute
  '/clients/$clientId/documents': typeof ClientsClientIdDocumentsRoute
  '/clients/$clientId/engagements': typeof ClientsClientIdEngagementsRouteWithChildren
  '/admin/users/$userId/assignments': typeof AdminUsersUserIdAssignmentsRoute
  '/clients/$clientId/engagements/$engagementId': typeof ClientsClientIdEngagementsEngagementIdRouteWithChildren
  '/clients/$clientId/engagements/$engagementId/documents/new': typeof ClientsClientIdEngagementsEngagementIdDocumentsNewRoute
  '/clients/$clientId/engagements/$engagementId/documents/': typeof ClientsClientIdEngagementsEngagementIdDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/clients': typeof ClientsRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/documents': typeof DocumentsIndexRoute
  '/clients/$clientId/documents': typeof ClientsClientIdDocumentsRoute
  '/clients/$clientId/engagements': typeof ClientsClientIdEngagementsRouteWithChildren
  '/admin/users/$userId/assignments': typeof AdminUsersUserIdAssignmentsRoute
  '/clients/$clientId/engagements/$engagementId': typeof ClientsClientIdEngagementsEngagementIdRouteWithChildren
  '/clients/$clientId/engagements/$engagementId/documents/new': typeof ClientsClientIdEngagementsEngagementIdDocumentsNewRoute
  '/clients/$clientId/engagements/$engagementId/documents': typeof ClientsClientIdEngagementsEngagementIdDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/clients': typeof ClientsRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/documents/': typeof DocumentsIndexRoute
  '/clients/$clientId/documents': typeof ClientsClientIdDocumentsRoute
  '/clients/$clientId/engagements': typeof ClientsClientIdEngagementsRouteWithChildren
  '/admin/users/$userId/assignments': typeof AdminUsersUserIdAssignmentsRoute
  '/clients/$clientId/engagements/$engagementId': typeof ClientsClientIdEngagementsEngagementIdRouteWithChildren
  '/clients/$clientId/engagements/$engagementId/documents/new': typeof ClientsClientIdEngagementsEngagementIdDocumentsNewRoute
  '/clients/$clientId/engagements/$engagementId/documents/': typeof ClientsClientIdEngagementsEngagementIdDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/clients'
    | '/health'
    | '/login'
    | '/logout'
    | '/admin/users'
    | '/documents/$documentId'
    | '/documents/'
    | '/clients/$clientId/documents'
    | '/clients/$clientId/engagements'
    | '/admin/users/$userId/assignments'
    | '/clients/$clientId/engagements/$engagementId'
    | '/clients/$clientId/engagements/$engagementId/documents/new'
    | '/clients/$clientId/engagements/$engagementId/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/clients'
    | '/health'
    | '/login'
    | '/logout'
    | '/admin/users'
    | '/documents/$documentId'
    | '/documents'
    | '/clients/$clientId/documents'
    | '/clients/$clientId/engagements'
    | '/admin/users/$userId/assignments'
    | '/clients/$clientId/engagements/$engagementId'
    | '/clients/$clientId/engagements/$engagementId/documents/new'
    | '/clients/$clientId/engagements/$engagementId/documents'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/clients'
    | '/health'
    | '/login'
    | '/logout'
    | '/admin/users'
    | '/documents/$documentId'
    | '/documents/'
    | '/clients/$clientId/documents'
    | '/clients/$clientId/engagements'
    | '/admin/users/$userId/assignments'
    | '/clients/$clientId/engagements/$engagementId'
    | '/clients/$clientId/engagements/$engagementId/documents/new'
    | '/clients/$clientId/engagements/$engagementId/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId/engagements': {
      id: '/clients/$clientId/engagements'
      path: '/$clientId/engagements'
      fullPath: '/clients/$clientId/engagements'
      preLoaderRoute: typeof ClientsClientIdEngagementsRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/$clientId/documents': {
      id: '/clients/$clientId/documents'
      path: '/$clientId/documents'
      fullPath: '/clients/$clientId/documents'
      preLoaderRoute: typeof ClientsClientIdDocumentsRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/$clientId/engagements/$engagementId': {
      id: '/clients/$clientId/engagements/$engagementId'
      path: '/$engagementId'
      fullPath: '/clients/$clientId/engagements/$engagementId'
      preLoaderRoute: typeof ClientsClientIdEngagementsEngagementIdRouteImport
      parentRoute: typeof ClientsClientIdEngagementsRoute
    }
    '/admin/users/$userId/assignments': {
      id: '/admin/users/$userId/assignments'
      path: '/$userId/assignments'
      fullPath: '/admin/users/$userId/assignments'
      preLoaderRoute: typeof AdminUsersUserIdAssignmentsRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/clients/$clientId/engagements/$engagementId/documents/': {
      id: '/clients/$clientId/engagements/$engagementId/documents/'
      path: '/documents'
      fullPath: '/clients/$clientId/engagements/$engagementId/documents/'
      preLoaderRoute: typeof ClientsClientIdEngagementsEngagementIdDocumentsIndexRouteImport
      parentRoute: typeof ClientsClientIdEngagementsEngagementIdRoute
    }
    '/clients/$clientId/engagements/$engagementId/documents/new': {
      id: '/clients/$clientId/engagements/$engagementId/documents/new'
      path: '/documents/new'
      fullPath: '/clients/$clientId/engagements/$engagementId/documents/new'
      preLoaderRoute: typeof ClientsClientIdEngagementsEngagementIdDocumentsNewRouteImport
      parentRoute: typeof ClientsClientIdEngagementsEngagementIdRoute
    }
  }
}

interface ClientsClientIdEngagementsEngagementIdRouteChildren {
  ClientsClientIdEngagementsEngagementIdDocumentsNewRoute: typeof ClientsClientIdEngagementsEngagementIdDocumentsNewRoute
  ClientsClientIdEngagementsEngagementIdDocumentsIndexRoute: typeof ClientsClientIdEngagementsEngagementIdDocumentsIndexRoute
}

const ClientsClientIdEngagementsEngagementIdRouteChildren: ClientsClientIdEngagementsEngagementIdRouteChildren =
  {
    ClientsClientIdEngagementsEngagementIdDocumentsNewRoute:
      ClientsClientIdEngagementsEngagementIdDocumentsNewRoute,
    ClientsClientIdEngagementsEngagementIdDocumentsIndexRoute:
      ClientsClientIdEngagementsEngagementIdDocumentsIndexRoute,
  }

const ClientsClientIdEngagementsEngagementIdRouteWithChildren =
  ClientsClientIdEngagementsEngagementIdRoute._addFileChildren(
    ClientsClientIdEngagementsEngagementIdRouteChildren,
  )

interface ClientsClientIdEngagementsRouteChildren {
  ClientsClientIdEngagementsEngagementIdRoute: typeof ClientsClientIdEngagementsEngagementIdRouteWithChildren
}

const ClientsClientIdEngagementsRouteChildren: ClientsClientIdEngagementsRouteChildren =
  {
    ClientsClientIdEngagementsEngagementIdRoute:
      ClientsClientIdEngagementsEngagementIdRouteWithChildren,
  }

const ClientsClientIdEngagementsRouteWithChildren =
  ClientsClientIdEngagementsRoute._addFileChildren(
    ClientsClientIdEngagementsRouteChildren,
  )

interface ClientsRouteChildren {
  ClientsClientIdDocumentsRoute: typeof ClientsClientIdDocumentsRoute
  ClientsClientIdEngagementsRoute: typeof ClientsClientIdEngagementsRouteWithChildren
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdDocumentsRoute: ClientsClientIdDocumentsRoute,
  ClientsClientIdEngagementsRoute: ClientsClientIdEngagementsRouteWithChildren,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface AdminUsersRouteChildren {
  AdminUsersUserIdAssignmentsRoute: typeof AdminUsersUserIdAssignmentsRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdAssignmentsRoute: AdminUsersUserIdAssignmentsRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  ClientsRoute: ClientsRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
